### PR TITLE
Added edgar allan poe content

### PR DESCRIPTION
**Pull request by JohnMeyer32**
This is Allan Edgar Poe's bio page. This should be good to add on right away but needs a link to the home page like the others. This is part of the issues 7 & 8:
https://github.com/lukeware/WATS-4020-Team-2/issues/7
https://github.com/lukeware/WATS-4020-Team-2/issues/8
Part 2/4

### CODE REVIEW

**Review by Hazel61 — APPROVED** [review]
Hi John, all is well. No conflicts reported. Merge away.

**Comment by DougJones866** [comment]
Everything looks all good, merge on.

**Review by dougjones866 — APPROVED** [review]
Everything looks all good, merge on.

**Comment by Okideveloper** [comment]
Love this poet... Merge away!

**Review by Okideveloper — COMMENTED** [review]
looks good to me

**Pull request closed without merging**
